from .big_category import router
from .category import router
from .collection import router
from .models import router
from .size import router
from .color import router
from .product import router
from .warehouse import router
from .product_size import router
from .order_status import router
from .client import router
from .order import router