from .category import router
from .collection import router
from .models import router
from .size import router
from .color import router
from .product import router
from .warehouse import router
from .warehouse_element import router
from .order_status import router
from .client import router
from .order import router
from .product_instance import router
from .price_list import router
from .price_list_element import router