version: '3.8'

services:

  api:
    container_name: api
    build: ./api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db

  client_frontend:
    build:
      context: ./client_frontend
      dockerfile: Dockerfile
    container_name: client_frontend
    volumes:
      - ./client_frontend:/var/www/html/app
    ports:
      - "8081:8080"

  admin_frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    restart: always
    container_name: admin_frontend
    ports:
      - "8080:80"

  db:
    container_name: db
    image: postgres
    ports:
      - '8001:5432' 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
  