"""add product_size

Revision ID: 03ee88615c32
Revises: f57cd306deae
Create Date: 2024-02-07 22:02:32.298929

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '03ee88615c32'
down_revision = 'f57cd306deae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_size_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'size_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_size_id_fkey', 'product', 'size', ['size_id'], ['id'])
    # ### end Alembic commands ###
