"""edit product_instance

Revision ID: 124aea2df269
Revises: 7a82f0401a22
Create Date: 2024-04-10 02:48:05.566225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '124aea2df269'
down_revision = '7a82f0401a22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
