"""edit client

Revision ID: 12bb8ad0a57d
Revises: 741dc3d885f7
Create Date: 2024-03-22 17:13:06.028847

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '12bb8ad0a57d'
down_revision = '741dc3d885f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('client', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('client', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('client', 'slug')
    op.drop_column('order', 'slug')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('client', 'created_at')
    op.drop_column('client', 'email')
    op.drop_column('client', 'phone')
    # ### end Alembic commands ###
