"""add warehouse_element

Revision ID: 1959fbc8db85
Revises: ee99a68475aa
Create Date: 2024-03-31 23:44:36.800394

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1959fbc8db85'
down_revision = 'ee99a68475aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouseelement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('warehouse', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('warehouseelement')
    # ### end Alembic commands ###
