"""add employee_status and department

Revision ID: 5344609ebbf2
Revises: 98777203b447
Create Date: 2024-04-01 01:36:40.994445

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5344609ebbf2'
down_revision = '98777203b447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employeestatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('client', 'sname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('employee', sa.Column('employee_status_id', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'employeestatus', ['employee_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'department_id')
    op.drop_column('employee', 'employee_status_id')
    op.alter_column('client', 'sname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('employeestatus')
    op.drop_table('department')
    # ### end Alembic commands ###
