"""add product_size2

Revision ID: 55b50f0bcf79
Revises: 03ee88615c32
Create Date: 2024-02-07 22:48:56.104837

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '55b50f0bcf79'
down_revision = '03ee88615c32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
