"""add delivery information

Revision ID: 63ef6f1fb116
Revises: 5344609ebbf2
Create Date: 2024-04-01 01:44:50.713179

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '63ef6f1fb116'
down_revision = '5344609ebbf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveryinformation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'employee_id')
    op.drop_table('deliveryinformation')
    # ### end Alembic commands ###
