"""add measurement

Revision ID: 64749650933d
Revises: 6eec85716108
Create Date: 2024-03-29 14:15:43.572415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '64749650933d'
down_revision = '6eec85716108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurementtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_guide_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['size_guide_id'], ['sizeguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurementvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('measurement_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_type_id'], ['measurementtype.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurementvalue')
    op.drop_table('measurementtype')
    # ### end Alembic commands ###
