"""add product_instance

Revision ID: 6588b708be58
Revises: 1959fbc8db85
Create Date: 2024-04-01 00:03:16.625095

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6588b708be58'
down_revision = '1959fbc8db85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('productsize')
    op.add_column('warehouseelement', sa.Column('product_instance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouseelement', 'productinstance', ['product_instance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouseelement', type_='foreignkey')
    op.drop_column('warehouseelement', 'product_instance_id')
    op.create_table('productsize',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='productsize_product_id_fkey'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], name='productsize_size_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='productsize_pkey')
    )
    op.drop_table('productinstance')
    # ### end Alembic commands ###
