"""edit client

Revision ID: 678393c07f1a
Revises: 12bb8ad0a57d
Create Date: 2024-03-22 18:31:38.561727

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '678393c07f1a'
down_revision = '12bb8ad0a57d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
