"""add price_list and price_list_element

Revision ID: 68ee40479c3b
Revises: 6588b708be58
Create Date: 2024-04-01 00:23:38.145743

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '68ee40479c3b'
down_revision = '6588b708be58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('beginning_at', sa.DateTime(), nullable=False),
    sa.Column('completion_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricelistelement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=True),
    sa.Column('product_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_list_id'], ['pricelist.id'], ),
    sa.ForeignKeyConstraint(['product_instance_id'], ['productinstance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricelistelement')
    op.drop_table('pricelist')
    # ### end Alembic commands ###
