"""add size_guide

Revision ID: 6eec85716108
Revises: da1145eee28a
Create Date: 2024-03-23 17:46:20.960759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6eec85716108'
down_revision = 'da1145eee28a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sizeguide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('model', sa.Column('size_guide_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model', 'sizeguide', ['size_guide_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_column('model', 'size_guide_id')
    op.drop_table('sizeguide')
    # ### end Alembic commands ###
