"""delete big_category

Revision ID: 741dc3d885f7
Revises: 2a524a838f13
Create Date: 2024-03-18 17:31:59.621513

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '741dc3d885f7'
down_revision = '2a524a838f13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_big_category_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'big_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('big_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_big_category_id_fkey', 'category', 'bigcategory', ['big_category_id'], ['id'])
    # ### end Alembic commands ###
