"""edit order

Revision ID: 7a82f0401a22
Revises: 7dbc99765440
Create Date: 2024-04-01 01:59:15.384887

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7a82f0401a22'
down_revision = '7dbc99765440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_information_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'deliveryinformation', ['delivery_information_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'delivery_information_id')
    # ### end Alembic commands ###
