"""add order_element

Revision ID: 7dbc99765440
Revises: 63ef6f1fb116
Create Date: 2024-04-01 01:55:32.369348

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7dbc99765440'
down_revision = '63ef6f1fb116'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderelement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('price_list_element_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['price_list_element_id'], ['pricelistelement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    op.drop_table('orderelement')
    # ### end Alembic commands ###
