"""init

Revision ID: 887cf6257964
Revises: 
Create Date: 2024-04-19 00:31:17.212395

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '887cf6257964'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('sname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('lname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('order', 'delivery_information_id')
    op.drop_column('order', 'personal_information_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('personal_information_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('delivery_information_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('order', 'postal_code')
    op.drop_column('order', 'city')
    op.drop_column('order', 'region')
    op.drop_column('order', 'email')
    op.drop_column('order', 'phone')
    op.drop_column('order', 'lname')
    op.drop_column('order', 'sname')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###
