"""add user, client, employee

Revision ID: 98777203b447
Revises: 68ee40479c3b
Create Date: 2024-04-01 01:10:55.461742

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98777203b447'
down_revision = '68ee40479c3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employment_at', sa.DateTime(), nullable=False),
    sa.Column('employment_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('sname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    op.drop_column('client', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'sname')
    op.drop_column('client', 'user_id')
    op.drop_table('employee')
    op.drop_table('user')
    # ### end Alembic commands ###
