"""delete field description model

Revision ID: ac773cb62d95
Revises: 64749650933d
Create Date: 2024-03-29 22:44:44.529313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ac773cb62d95'
down_revision = '64749650933d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
