"""edit order

Revision ID: c285c250827f
Revises: 9929b77b7909
Create Date: 2024-04-21 19:44:40.443684

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c285c250827f'
down_revision = '9929b77b7909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'order_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'order_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
