"""edit employee

Revision ID: cd47f078647b
Revises: 887cf6257964
Create Date: 2024-04-19 16:25:52.507094

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd47f078647b'
down_revision = '887cf6257964'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('employee', sa.Column('sname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('employee', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employee', 'employee_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employee', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employee', 'employment_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'employment_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('employee', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee', 'employee_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employee', 'sname')
    op.drop_column('employee', 'name')
    # ### end Alembic commands ###
