"""edit  category

Revision ID: d0f5e0f61791
Revises: ee4503bd474a
Create Date: 2024-01-26 09:11:20.304749

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd0f5e0f61791'
down_revision = 'ee4503bd474a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
