"""edit warehouse element

Revision ID: d254fd9ad100
Revises: 124aea2df269
Create Date: 2024-04-11 17:28:48.812772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd254fd9ad100'
down_revision = '124aea2df269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productinstance', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('productinstance', 'size_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('warehouseelement', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouseelement', 'count')
    op.alter_column('productinstance', 'size_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('productinstance', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
