"""add detail

Revision ID: da1145eee28a
Revises: 678393c07f1a
Create Date: 2024-03-23 16:41:05.068624

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'da1145eee28a'
down_revision = '678393c07f1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('model', sa.Column('detail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model', 'detail', ['detail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_column('model', 'detail_id')
    op.drop_table('detail')
    # ### end Alembic commands ###
