"""edit price_list_elements

Revision ID: e13d0ba624f0
Revises: d254fd9ad100
Create Date: 2024-04-14 19:22:34.246847

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e13d0ba624f0'
down_revision = 'd254fd9ad100'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricelist', 'completion_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('pricelistelement', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricelistelement', 'price')
    op.alter_column('pricelist', 'completion_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
