"""add delete cascade big_category

Revision ID: f57cd306deae
Revises: 8997f9273a47
Create Date: 2024-02-02 14:51:37.730107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f57cd306deae'
down_revision = '8997f9273a47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
